# .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or whatever your default branch is

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Match your development environment
          cache: 'npm'

      - name: Install Dependencies 📦
        run: npm ci

      - name: Build Project 🏗️
        run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The directory your build command outputs to
